const express = require("express");
const app = express();

const path = require("path");
const bodyParser = require('body-parser');
const exphbs = require('express-handlebars');
var nodemailer = require('nodemailer');
var mongoose = require("mongoose");

const HTTP_PORT = process.env.PORT || 8080;

app.use(bodyParser.urlencoded({ extended: true }));
app.engine('.hbs', exphbs({ extname: '.hbs' }));
app.set('view engine', '.hbs');

var transporter = nodemailer.createTransport({
  host: "smtp.mailtrap.io",
  port: 2525,
  auth: {
    user: "ac110aa0de2962", //generated by Mailtrap
    pass: "fecbd95e009b93" //generated by Mailtrap
  }
});


// mongodb connection and code
var Schema = mongoose.Schema;
mongoose.connect("mongodb+srv://dbUser:4755@senecaweb.ccrea.mongodb.net/web322_assignment?retryWrites=true&w=majority");
var userSchema = new Schema({
  "email": {
    type: String,
    unique: true
  },
  "firstName": String,
  "lastName": String,
  "password": String,
  "birthdate": Date  
});
var User = mongoose.model("users", userSchema);

/* User.find({ email: "srahman71@myseneca.ca" })
  .exec()
  .then((user) => {
    if(!user) {
      console.log("No user could be found");
    } else {
      console.log(user);
    }
  })
  .catch((err) => {
    console.log(`There was an error: ${err}`);
  });
});
 */

// call this function after the http server starts listening for requests
function onHttpStart() {
  console.log("Express http server listening on: " + HTTP_PORT);
}

app.use(express.static(path.join(__dirname, 'public')));

// setup a 'route' to listen on the default url path (http://localhost)
app.get("/", function(req,res){
    res.sendFile(path.join(__dirname, 'views', 'index.html'));
});

app.get("/rooms", function(req,res){
    res.sendFile(path.join(__dirname, 'views', 'roomListing.html'));
});

app.get("/signup", function(req,res){
    res.sendFile(path.join(__dirname, 'views', 'signup.html'));
});
  
// setup http server to listen on HTTP_PORT
app.listen(HTTP_PORT, onHttpStart);

// Respond to the client with data
app.post("/dashboard", (req, res) => {
  var signupData = req.body;

  // creating model for db insert
  var user = new User({
    "email": signupData.email,
    "firstName": signupData.firstname,
    "lastName": signupData.lastname,
    "password": signupData.password,
    "birthdate": new Date(signupData.date)
  });

  // save the user
 user.save((err) => {
  if(err) {
    console.log(`There was an error saving the user : ${err}`);
  } else {
    console.log("The user was saved to the users collection");
  }
 });

  // code to mail confirmation of signup
  var mailOptions = {
    from: 'rahmanshamima328@gmail.com',
    to: signupData.email,
    subject: 'Signup confirmation',
    text: 'Welcome...Thank you for signing up ' + signupData.firstname + ' ' + signupData.lastname +'.'
  };
  transporter.sendMail(mailOptions, function(error, info){
    if (error) {
      console.log(error);
    } else {
      console.log('Email sent: ' + info.response);
    }
  });

  // forward the user to a dashboard
  res.render('dashboard', {
    data: signupData,
    layout: false 
  }); 
});
